// Generated by CoffeeScript 1.4.0
var app, assets, express, i18n, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

i18n = require('i18next');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

i18n.init({
  resGetPath: 'locales/__lng__.json',
  fallbackLng: "pl-PL"
});

i18n.addPostProcessor("jade", function(val, key, opts) {
  return require('jade').compile(val, opts)();
});

i18n.registerAppHelper(app);

app.use(i18n.handle);

app.get('/*', require('./controllers/home').index);

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
